field: 59e0cbb3-e5c1-4202-aded-220aecef6e07 # Resume Blocks
fieldLayouts:
  e667add5-be7d-47b3-9420-be069536759a:
    tabs:
      -
        fields:
          5e9f447d-cf2f-4c03-9e6e-ebe07ae771fe: # Attendance Dates
            required: false
            sortOrder: 4
          5ea67989-623f-4c1b-b05d-4b3a1b0101f6: # Main Content
            required: false
            sortOrder: 5
          129a5baa-a91b-4c89-bb3a-ca5118cfa43c: # Degree Title
            required: false
            sortOrder: 3
          a1c9e1f0-740b-49c8-a06a-14405ce4a443: # School Name
            required: false
            sortOrder: 1
          b01e6431-581e-4b15-870d-2c1b6ea3029b: # School Location
            required: false
            sortOrder: 2
        name: Content
        sortOrder: 1
fields:
  5e9f447d-cf2f-4c03-9e6e-ebe07ae771fe: # Attendance Dates
    contentColumnType: text
    fieldGroup: null
    handle: attendanceDates
    instructions: ''
    name: 'Attendance Dates'
    searchable: true
    settings:
      charLimit: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: 'e.g. August 2008 - May 2012'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  5ea67989-623f-4c1b-b05d-4b3a1b0101f6: # Main Content
    contentColumnType: string
    fieldGroup: null
    handle: mainContent
    instructions: 'The main body that you wish to write about what you did at this school.'
    name: 'Main Content'
    searchable: true
    settings:
      cleanupHtml: '1'
      columnType: text
      configFile: ''
      purifyHtml: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  129a5baa-a91b-4c89-bb3a-ca5118cfa43c: # Degree Title
    contentColumnType: text
    fieldGroup: null
    handle: degreeTitle
    instructions: ''
    name: 'Degree Title'
    searchable: true
    settings:
      charLimit: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: 'e.g. Bachelor of Science'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  a1c9e1f0-740b-49c8-a06a-14405ce4a443: # School Name
    contentColumnType: text
    fieldGroup: null
    handle: schoolName
    instructions: ''
    name: 'School Name'
    searchable: true
    settings:
      charLimit: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: 'e.g. University of Oklahoma'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b01e6431-581e-4b15-870d-2c1b6ea3029b: # School Location
    contentColumnType: text
    fieldGroup: null
    handle: schoolLocation
    instructions: ''
    name: 'School Location'
    searchable: true
    settings:
      charLimit: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: 'e.g. Norman, OK'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: education
name: Education
sortOrder: 4
