field: 59e0cbb3-e5c1-4202-aded-220aecef6e07 # Resume Blocks
fieldLayouts:
  96b1bb31-02b7-4102-9a17-5be5db081dc9:
    tabs:
      -
        elements:
          -
            fieldUid: afbe8279-652f-48ee-983f-65a2bcc79c87 # Heading
            instructions: null
            label: null
            required: 1
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  afbe8279-652f-48ee-983f-65a2bcc79c87: # Heading
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: 'A Heading'
    name: Heading
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: 'e.g. About'
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: heading
name: Heading
sortOrder: 1
