field: 59e0cbb3-e5c1-4202-aded-220aecef6e07 # Resume Blocks
fieldLayouts:
  e2d3e1ec-7a81-4185-a52b-3352c3866e17:
    tabs:
      -
        elements:
          -
            fieldUid: f080972b-de4b-4ebe-90b8-c1dc5a3bb815 # List Title
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 71317842-4cbf-4e25-b59e-0e913fb93ab4 # List Body
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  71317842-4cbf-4e25-b59e-0e913fb93ab4: # List Body
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: listBody
    instructions: 'Body of your list.'
    name: 'List Body'
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  f080972b-de4b-4ebe-90b8-c1dc5a3bb815: # List Title
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: listTitle
    instructions: 'Title of your list.'
    name: 'List Title'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: list
name: List
sortOrder: 7
