field: 59e0cbb3-e5c1-4202-aded-220aecef6e07 # Resume Blocks
fieldLayouts:
  e0f79c5c-3b3c-4dd4-b7a7-9e21d49cac48:
    tabs:
      -
        fields:
          246ac786-a0a2-4cc2-9753-faf42e7db69d: # Skill Title
            required: false
            sortOrder: 1
          465b0663-a60a-44ba-9868-6299b27b2e73: # Skill Percentage
            required: false
            sortOrder: 2
        name: Content
        sortOrder: 1
fields:
  246ac786-a0a2-4cc2-9753-faf42e7db69d: # Skill Title
    contentColumnType: text
    fieldGroup: null
    handle: skillTitle
    instructions: 'The title of your skill'
    name: 'Skill Title'
    searchable: true
    settings:
      charLimit: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  465b0663-a60a-44ba-9868-6299b27b2e73: # Skill Percentage
    contentColumnType: smallint(3)
    fieldGroup: null
    handle: skillPercentage
    instructions: 'From 0 - 100, how proficient you are'
    name: 'Skill Percentage'
    searchable: true
    settings:
      decimals: '0'
      max: '100'
      min: '0'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
handle: skillBar
name: 'Skill Bar'
sortOrder: 3
