field: 59e0cbb3-e5c1-4202-aded-220aecef6e07 # Resume Blocks
fieldLayouts:
  e0f79c5c-3b3c-4dd4-b7a7-9e21d49cac48:
    tabs:
      -
        elements:
          -
            fieldUid: 246ac786-a0a2-4cc2-9753-faf42e7db69d # Skill Title
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 465b0663-a60a-44ba-9868-6299b27b2e73 # Skill Percentage
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  246ac786-a0a2-4cc2-9753-faf42e7db69d: # Skill Title
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: skillTitle
    instructions: 'The title of your skill'
    name: 'Skill Title'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  465b0663-a60a-44ba-9868-6299b27b2e73: # Skill Percentage
    columnSuffix: null
    contentColumnType: smallint(3)
    fieldGroup: null
    handle: skillPercentage
    instructions: 'From 0 - 100, how proficient you are'
    name: 'Skill Percentage'
    searchable: true
    settings:
      decimals: 0
      defaultValue: null
      max: 100
      min: 0
      prefix: null
      previewCurrency: ''
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
handle: skillBar
name: 'Skill Bar'
sortOrder: 3
