fieldLayouts:
  729e4d40-6837-4f3a-8c13-e3ad08960741:
    tabs:
      -
        elements:
          -
            instructions: null
            label: 'Full Name'
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: b1728805-d5d0-44a4-a498-b609f35b1361
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: c5ff41e6-e696-45f2-b7c3-9ae40be874bc
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 7f7aa23e-bcb7-4e8b-825b-28bcd7f1e639
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: 'Basic Info'
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 59e0cbb3-e5c1-4202-aded-220aecef6e07
            required: true
            type: craft\fieldlayoutelements\CustomField
        name: Resume
        sortOrder: 2
      -
        elements:
          -
            fieldUid: 388a1cf0-91d1-46e9-864e-6177844d9933
            required: true
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 3ad3daad-89f2-418a-89e5-a493884e8ba9
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Settings
        sortOrder: 3
handle: homepage
hasTitleField: true
name: GHomepage
section: 3bce26a2-451a-4f0a-88c8-731f7e278e36
sortOrder: 0
titleFormat: null
