contentColumnType: text
fieldGroup: 20d0b3c0-e1c3-4ba1-8258-808332239fba # Default
handle: emailAddress
instructions: 'Your personal email address'
name: 'Email Address'
searchable: true
settings:
  charLimit: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: 'e.g. example@gmail.com'
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
