contentColumnType: text
fieldGroup: 20d0b3c0-e1c3-4ba1-8258-808332239fba # Default
handle: phoneNumber
instructions: 'Optional phone number to display'
name: 'Phone Number'
searchable: true
settings:
  charLimit: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: 'e.g. 555.555.5555 -or- 555-555-5555'
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
