columnSuffix: null
contentColumnType: string
fieldGroup: 20d0b3c0-e1c3-4ba1-8258-808332239fba # Default
handle: resumeBlocks
instructions: ''
name: 'Resume Blocks'
searchable: true
settings:
  contentTable: '{{%matrixcontent_resumeblocks}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
