columnSuffix: null
contentColumnType: string
fieldGroup: 20d0b3c0-e1c3-4ba1-8258-808332239fba # Default
handle: theme
instructions: 'The design theme for your template'
name: Theme
searchable: true
settings:
  optgroups: true
  options:
    -
      __assoc__:
        -
          - label
          - Cerulean
        -
          - value
          - cerulean
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Cosmo
        -
          - value
          - cosmo
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Custom
        -
          - value
          - custom
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Cyborg
        -
          - value
          - cyborg
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Darkly
        -
          - value
          - darkly
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Flatly
        -
          - value
          - flatly
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Journal
        -
          - value
          - journal
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Lumen
        -
          - value
          - lumen
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Paper
        -
          - value
          - paper
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Readable
        -
          - value
          - readable
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Sandstone
        -
          - value
          - sandstone
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Simplex
        -
          - value
          - simplex
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Slate
        -
          - value
          - slate
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Spacelab
        -
          - value
          - spacelab
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Superhero
        -
          - value
          - superhero
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - United
        -
          - value
          - united
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Yeti
        -
          - value
          - yeti
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
