contentColumnType: text
fieldGroup: 20d0b3c0-e1c3-4ba1-8258-808332239fba # Default
handle: webSite
instructions: 'An optional personal web site to link to yourself'
name: 'Web Site'
searchable: true
settings:
  charLimit: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: 'http://somewhere.com'
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
