dateModified: 1648845207
email:
  fromEmail: alkrauss48@gmail.com
  fromName: Resume
  template: null
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    0d19ae45-54ba-4439-831a-bb675aa51e81: List # List
    3ad3daad-89f2-418a-89e5-a493884e8ba9: 'Google Analytics ID' # Google Analytics ID
    3b17c04c-c155-41c8-b46a-e9b3d9058c0e: 'Public Schema' # Public Schema
    3bce26a2-451a-4f0a-88c8-731f7e278e36: Resume # Resume
    5c40e9cb-7114-4a81-bb5a-7e41c1d1b25e: 'Resume Haus (en-US)' # Resume Haus (en-US)
    5e7c1a3c-fb71-4178-8ece-e873e7e0d0cc: 'Job Title' # Job Title
    5e9f447d-cf2f-4c03-9e6e-ebe07ae771fe: 'Attendance Dates' # Attendance Dates
    5ea67989-623f-4c1b-b05d-4b3a1b0101f6: 'Main Content' # Main Content
    6e129f3a-b85f-4131-95fc-e202a39a8a73: 'Company Location' # Company Location
    6e507de9-c3e2-4201-a43b-e837520e817a: Heading # Heading
    7f7aa23e-bcb7-4e8b-825b-28bcd7f1e639: 'Phone Number' # Phone Number
    9ed3efca-eeda-43ef-9c89-8983717ed277: 'Skill Bar' # Skill Bar
    20d0b3c0-e1c3-4ba1-8258-808332239fba: Default # Default
    30f68721-b84b-4481-af19-8dce25d3560d: 'Company name' # Company name
    59e0cbb3-e5c1-4202-aded-220aecef6e07: 'Resume Blocks' # Resume Blocks
    98a69d94-8845-4e75-a790-a8349847ad4f: Body # Body
    129a5baa-a91b-4c89-bb3a-ca5118cfa43c: 'Degree Title' # Degree Title
    246ac786-a0a2-4cc2-9753-faf42e7db69d: 'Skill Title' # Skill Title
    388a1cf0-91d1-46e9-864e-6177844d9933: Theme # Theme
    465b0663-a60a-44ba-9868-6299b27b2e73: 'Skill Percentage' # Skill Percentage
    002700d7-3cc2-48c4-82ee-439ae5a69938: Default # Default
    725539d5-3688-4c5d-9d49-42c27cee20eb: 'User Photos' # User Photos
    3579409d-3cc9-4c7a-a65e-a675bfe120a3: 'Resume Haus (en-US)' # Resume Haus (en-US)
    71317842-4cbf-4e25-b59e-0e913fb93ab4: 'List Body' # List Body
    a1c9e1f0-740b-49c8-a06a-14405ce4a443: 'School Name' # School Name
    ab190f80-0964-4731-abc6-ab7cd74765b7: Education # Education
    afbe8279-652f-48ee-983f-65a2bcc79c87: Heading # Heading
    b01e6431-581e-4b15-870d-2c1b6ea3029b: 'School Location' # School Location
    b2fa4a40-6b05-4a60-9926-716acfaf44be: 'Work Experience' # Work Experience
    b8ecbf09-4ee4-4ccc-98be-1531b42d28b1: Text # Text
    b1728805-d5d0-44a4-a498-b609f35b1361: 'Web Site' # Web Site
    bb855769-7e53-4719-99d3-1291dc1ea6cd: Body # Body
    c5ff41e6-e696-45f2-b7c3-9ae40be874bc: 'Email Address' # Email Address
    c667b680-8bdb-4574-a436-74f70b26caa0: 'Main Content' # Main Content
    ce87aa87-1e37-434b-a3a7-26849040f991: Tags # Tags
    d5c91b95-b14e-408f-b385-d26531ac875b: Member # Member
    d77a7ce8-8506-448a-90bc-8f425f273d60: 'Company Website' # Company Website
    f080972b-de4b-4ebe-90b8-c1dc5a3bb815: 'List Title' # List Title
    f76db532-04ed-40c2-89d4-bef9ec936640: GHomepage # GHomepage
    f513dbac-d077-49f1-9d17-7ca2343506c6: 'Dates Employed' # Dates Employed
plugins:
  contact-form:
    enabled: '0'
    licenseKey: null
    schemaVersion: 1.0.0
    settings:
      allowAttachments: '1'
      honeypotField: ''
      prependSender: 'Resume Haus Submission: '
      prependSubject: 'New Resume Haus Submission'
      toEmail: resumehaus@mailinator.com
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
system:
  edition: pro
  live: true
  name: 'Resume Haus'
  schemaVersion: 3.7.33
  timeZone: UTC
